### ISSUE TITLE
Generator hangs on home.less

### ISSUE THREAD

**Issue by jboothe** [dustinspecker/generator-ng-poly#137] opened 2015-04-05 02:28 UTC
Just installed version 0.7.3 and generator hangs when building out the home.less file.

Here are the options selected:
```
? What is the app's name? appfour
? Which version of Angular should be used? 1.3.*
? What host should the app run on? localhost
? Which port should the app run on? 4000
? Which folder should the app be developed in? app
? Which is the preferred markup language? HTML
? Which is the preferred application scripting language? JavaScript
? Want to use Controller As syntax? Yes
? By default, should the route generator create controllers? Yes
? Should functions be defined and passed instead of defined inline (in callbacks)? Yes
? Want to use named functions instead of anonymous? Yes
? Where should unit tests be saved? app
? Which is the preferred test scripting language? JavaScript
? Which is the preferred unit testing framework? Jasmine
? Which is the preferred e2e testing framework? Jasmine
? Which is the preferred style language? LESS
? Should Polymer support be enabled? No
? Should a framework be setup? Bootstrap with UI Bootstrap
? Should ngRoute be used instead of UI Router? No
? Which additional Bower components should be installed? Angular Animate, Angular Cookies, Angular Messages, Angular Resource, Angular Sanitize, Angular Touch, Font Awesome
```
....
It creates these files and then hangs at home.less and never completes:
```
create app/home/home.js
   create e2e/home/home.po.js
   create e2e/home/home_test.js
   create app/home/home-controller.js
   create app/home/home-controller_test.js
   create app/home/home.tpl.html
   create app/home/home.less
```
Let me know if there is anything else I can provide.

**Comment by dustinspecker** [comment] 2015-04-05 02:47
Hi, Jeff. Are you using Node 0.12 by any chance? If so, this is probably a duplicate of #131, which I believe is a Node or Yeoman bug at the moment. This isn't happening on Node 0.10 to my knowledge.

Once ng-poly outputs creating the home module files, you can terminate the session `CTRL+C` and the project should be good to go. There haven't been any reported issues outside of the initial scaffold. Sorry for the inconvenience.

**Comment by jboothe** [comment] 2015-04-05 04:13
Yes, I was using 0.12.2. So went back to 0.10.24. Now I'm seeing strange behavior when running `gulp` after the gen. When I type `gulp` in the project root, I am taken to the the gulp folder of the project. Typing  `gulp` from there launches the project. The project seems to run fine from there but never seen that behavior before!?

**Closed** 2015-04-09 05:42 UTC
